### PR TITLE
Allow any Rails version

### PR DESCRIPTION
**Pull request by Nowaker**

### CODE REVIEW

**Comment by andyatkinson** [comment]
I agree. Actually we are trying to use the Rack Attack dashboard gem and using a newer version of Rails. I removed the dependency on specific rails versions in the dashboard gem, but now I've realized the same thing is happening for this gem. Are there specific major version differences between rails 4, 5, 6 that would break this gem?

**Comment by Nowaker** [comment]
@andyatkinson No, it works on all versions with my change.

**Comment by Nowaker** [comment]
@TylerRick Ping.

**Comment by TylerRick** [comment]
Thank you for the PR and my apologies for the delay in merging this! I hope you were able to use your fork in the meantime.

This has been resolved in the latest version, 1.0.0.

**Pull request closed without merging**
